# Домашнее задание. Разложить матрицу в SVD.

Цель: Выполнить сингулярное разложение в python и записать получившуюся матрицу преобразования для следующих матриц: 1)A=[3 7 5 2] 2)B=[0 1 3 2 3 1 0 1 0] 3)C=[5 7 6 4 2 1 3 4 1 3 3 4 5 4 1]

1) A = [3 7 5 2]. Представим заданную матрицу размерностью 2 X 2 и выполним ее сингулярное разложение вида A = U*S*V<sup>T</sup>:

In [1]:
import numpy as np
import scipy.linalg as la
np.set_printoptions(precision = 3)
np.set_printoptions(suppress = True)

A = np.array([[3, 7], [5, 2]])
print('Исходная матрица A:')
print('A = \n', A)
U, s, VT = la.svd(A)
print('SVD разложение:')
print('U = \n', U)
print('S = \n', s)
print('VT = \n', VT)

Исходная матрица A:
A = 
 [[3 7]
 [5 2]]
SVD разложение:
U = 
 [[-0.851 -0.526]
 [-0.526  0.851]]
S = 
 [8.713 3.328]
VT = 
 [[-0.595 -0.804]
 [ 0.804 -0.595]]


В качестве проверки восстановим исходную матрицу:

In [2]:
Sigma = np.zeros((A.shape[0], A.shape[1]))
Sigma[:np.min(A.shape), :np.min(A.shape)] = np.diag(s)
AR = U.dot(Sigma.dot(VT))
print('Восстановленная матрица A = \n', AR)

Восстановленная матрица A = 
 [[3. 7.]
 [5. 2.]]


2) В = [0 1 3 2 3 1 0 1 0]. Представим заданную матрицу размерностью 3 X 3 и выполним ее сингулярное разложение вида B = U*S*V<sup>T</sup>:

In [3]:
import numpy as np
import scipy.linalg as la

B = np.array([[0, 1, 3], [2, 3, 1], [0, 1, 0]])
print('Исходная матрица B:')
print('B = \n', B)
U, s, VT = la.svd(B)
print('SVD разложение:')
print('U = \n', U)
print('S = \n', s)
print('VT = \n', VT)

Исходная матрица B:
B = 
 [[0 1 3]
 [2 3 1]
 [0 1 0]]
SVD разложение:
U = 
 [[-0.567  0.823  0.044]
 [-0.807 -0.543 -0.232]
 [-0.167 -0.167  0.972]]
S = 
 [4.34  2.416 0.572]
VT = 
 [[-0.372 -0.727 -0.578]
 [-0.45  -0.403  0.797]
 [-0.812  0.556 -0.177]]


В качестве проверки восстановим исходную матрицу:

In [4]:
Sigma = np.zeros((B.shape[0], B.shape[1]))
Sigma[:np.min(B.shape), :np.min(B.shape)] = np.diag(s)
BR = U.dot(Sigma.dot(VT))
print('Восстановленная матрица B = \n', BR)

Восстановленная матрица B = 
 [[0. 1. 3.]
 [2. 3. 1.]
 [0. 1. 0.]]


2) C = [5 7 6 4 2 1 3 4 1 3 3 4 5 4 1]. Представим заданную матрицу размерностью 3 X 5 и выполним ее сингулярное разложение вида C = U*S*V<sup>T</sup>:

In [5]:
import numpy as np
import scipy.linalg as la

C = np.array([[5, 7, 6, 4, 2], [1, 3, 4, 1, 3], [3, 4, 5, 4, 1]])
print('Исходная матрица C:')
print('C = \n', C)
U, s, VT = la.svd(C)
print('SVD разложение:')
print('U = \n', U)
print('S = \n', s)
print('VT = \n', VT)

Исходная матрица C:
C = 
 [[5 7 6 4 2]
 [1 3 4 1 3]
 [3 4 5 4 1]]
SVD разложение:
U = 
 [[-0.759  0.234 -0.607]
 [-0.364 -0.926  0.097]
 [-0.539  0.295  0.789]]
S = 
 [14.947  2.727  1.464]
VT = 
 [[-0.387 -0.573 -0.583 -0.372 -0.211]
 [ 0.415  0.015 -0.302  0.437 -0.739]
 [-0.391 -0.548  0.472  0.563 -0.091]
 [-0.437  0.367 -0.531  0.548  0.303]
 [ 0.579 -0.486 -0.255  0.232  0.556]]


В качестве проверки восстановим исходную матрицу:

In [6]:
Sigma = np.zeros((C.shape[0], C.shape[1]))
Sigma[:np.min(C.shape), :np.min(C.shape)] = np.diag(s)
CR = U.dot(Sigma.dot(VT))
print('Восстановленная матрица C = \n', CR)

Восстановленная матрица C = 
 [[5. 7. 6. 4. 2.]
 [1. 3. 4. 1. 3.]
 [3. 4. 5. 4. 1.]]
